sudo: false
language: ruby
rvm:
  - 2.6.0
env:
  global:
    - CC_TEST_REPORTER_ID=b6c01da2aaa6bb76679393e3df5e310799db3bf585260a93c733a96f8e361afe
addons:
  postgresql: "9.6"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
